### ISSUE TITLE
Create plotting functions 

### ISSUE THREAD

**Issue by imarkonis** [imarkonis/schemata#10]
plot_basin(x), x is a vector with BAS_ID values.

ggplot type, with facet_wrap to cover length(x) > 1.

plot_basins(x), x is an sf object.

Again ggplot type if possible. Plots a map highlighting different rivers.

(feel free to change the function names to something more suitable)

**Comment by Jorub** [comment]
Created two functions. geom_sf does not accept discrete colors, created a 'long' color gradient, and replaced BAS_ID with Indices to avoid neighbors having the same color.
