### ISSUE TITLE
Transform lines to rivers

### ISSUE THREAD

**Issue by imarkonis** [imarkonis/schemata#8]
Instead of having each pilot_area element as a line, e.g., `plot(eu_rivers$geometry[1:12])`, we need to aggregate them to multi-line river objects. Then plot(eu_rivers$geometry[1:13]) should give 12 rivers.

**Comment by Jorub** [comment]
Extracted more detailed hydroshed data from GEE using RGEE (https://github.com/r-spatial/rgee) and turned into _multilinestring_ based on BAS_ID.
